# Generated by Django 4.2.6 on 2023-10-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("ikon", models.BooleanField()),
                ("epic", models.BooleanField()),
                ("avg_day_price", models.PositiveBigIntegerField()),
            ],
        ),
    ]
